enum class Assembly {
    DECLARE,
    PUSH_TEMP,
    POP_TEMP,
    DEFINE_FUNCTION,
    END_DEFINE_FUNCTION,
    ADD_FUNCTION_ARGUMENT,
    CALL,
    RETURN,
    NAMESPACE_ACCESS,
    ADD,
    ASSEMBLY_MAX
};